"""Tools for managing xgen within pini pipeline."""

import logging

from maya import cmds

from pini import qt, pipe
from pini.utils import (
    Dir, File, single, abs_path, plural, nice_size, to_str, TMP)

from maya_pini import open_maya as pom
from maya_pini.utils import to_parent

_LOGGER = logging.getLogger(__name__)

XGEN_TYPES = (
    'xgmPalette',  # legacy XGen collection
    'xgmSplineDescription',  # interactive groom splines
)


class _XgenSidecar(File):
    """Represents an xgen sidecar file.

    These are autogenerated by xgen in the scene folder for each collection.
    """

    def __init__(self, path):
        """Constructor.

        Args:
            path (str): path to sidecar
        """
        super().__init__(path)

        self.ns = None
        if self.filename.count('__') == 1:
            self.work_base, self.col = self.base.split('__', 1)
        else:
            self.work_base, _ = self.base.split('__', 1)
            _, self.col = self.base.rsplit('__', 1)
            self.ns = self.base[len(self.work_base) + 2: -len(self.col) - 2]

    @property
    def data_dir(self):
        """Read data dir from this sidecar.

        This is where xgen stores the hard data for the system.

        Returns:
            (Dir): data dir
        """
        return self._parse_data()['data_dir']

    @property
    def proj_dir(self):
        """Read project dir from this sidecar.

        This is where xgen stores working data.

        Returns:
            (Dir): project dir
        """
        return self._parse_data()['proj_dir']

    def _find_lines(self, key=None, val=None, body=None):
        """Search lines of this file.

        Lines of importance are generally key/val pairs separated by a space.

        Args:
            key (str): match only this key
            val (str): match only this value
            body (str): override file body (to avoid multiple disk reads)

        Returns:
            (str list): matching lines
        """
        _lines = []
        for _line in self.read_lines(body=body):
            _tokens = _line.split()
            if len(_tokens) != 2:
                continue
            _key, _val = _tokens
            if key and _key != key:
                continue
            if val and _val != val:
                continue
            _lines.append(_line)
        return _lines

    def _parse_data(self):
        """Parse data in this file.

        Returns:
            (dict): important data
        """
        _proj_path = _data_path = None
        _data_lines = set()
        _proj_lines = set()
        for _line in self.read_lines():
            _tokens = _line.split()
            if len(_tokens) != 2:
                continue
            _key, _val = _tokens
            _clean_line = _line.strip('\n\n /')
            if _key == 'xgProjectPath':
                _val = _val.rstrip('/')
                _proj_lines.add(_clean_line)
                _LOGGER.debug('   - CUR %s %s', _key, _val)
                if not _proj_path:
                    _proj_path = _val
                elif _proj_path == _val:
                    pass
                else:
                    raise NotImplementedError

            elif _key == 'xgDataPath':
                _val = _val.rstrip('/')
                _LOGGER.debug('   - CUR %s %s', _key, _val)
                _data_lines.add(_clean_line)
                if not _data_path:
                    _data_path = _val
                elif _data_path == _val:
                    pass
                else:
                    raise NotImplementedError

        _LOGGER.debug(' - PROJ PATH %s', _proj_path)
        _LOGGER.debug(' - DATA PATH %s', _data_path)

        _data_dir = Dir(_resolve_proj(_data_path))
        if _data_dir.filename != self.col:
            raise RuntimeError(_data_dir, self.col)

        return {
            'data_dir': _data_dir,
            'data_path': _data_path,
            'proj_dir': Dir(_resolve_proj(_proj_path)),
            'proj_path': _proj_path,
            'proj_lines': sorted(_proj_lines),
            'data_lines': sorted(_data_lines)}

    def rename_patch(self, cur_name, new_name, force=False):
        """Rename patch (ie. a mesh) in this file.

        Args:
            cur_name (str): current mesh name
            new_name (str): new mesh name
            force (bool): update file without confirmation
        """
        _body = self.read()
        for _cur_line in self._find_lines(key='name', val=cur_name, body=_body):
            assert _cur_line.count(cur_name) == 1
            _new_line = _cur_line.replace(cur_name, new_name)
            _body = _body.replace(_cur_line, _new_line)
        self.write(_body, diff=True, force=force)

    def set_data_path(self, path, force=False):
        """Set data path in this file.

        Args:
            path (Dir): path to apply
            force (bool): update file without confirmation
        """
        _LOGGER.info('SET DATA PATH %s', path)
        _data = self._parse_data()
        _orig_body = _body = self.read()
        _cur_proj_path = _data['data_path']
        for _cur_line in _data['data_lines']:
            _LOGGER.info(' - CUR LINE %s', _cur_line)
            _new_line = _cur_line.replace(_cur_proj_path, to_str(path))
            _LOGGER.info(' - NEW LINE %s', _new_line)
            assert _cur_proj_path in _cur_line
            assert _cur_line in _body
            _body = _body.replace(_cur_line, _new_line)
        if _orig_body == _body:
            _LOGGER.info(' - NO CHANGE REQUIRED')
            return
        self.write(_body, diff=True, force=force)

    def set_proj_path(self, path):
        """Set project path for this file.

        Args:
            path (Dir): path to apply
        """
        _LOGGER.info('SET PROJ PATH %s', path)
        _data = self._parse_data()
        _orig_body = _body = self.read()
        _cur_proj_path = _data['proj_path']
        for _cur_line in _data['proj_lines']:
            _LOGGER.info(' - CUR LINE %s', _cur_line)
            _new_line = _cur_line.replace(_cur_proj_path, to_str(path))
            _LOGGER.info(' - NEW LINE %s', _new_line)
            assert _cur_proj_path in _cur_line
            assert _cur_line in _body
            _body = _body.replace(_cur_line, _new_line)
        if _orig_body == _body:
            _LOGGER.info(' - NO CHANGE REQUIRED')
            return
        raise NotImplementedError


class _XgenCol(pom.CTransform):
    """Represents an xgen collection/palette node."""

    @property
    def data_dir(self):
        """Obtain current data dir for this collection.

        Returns:
            (Dir): current data dir
        """
        return self.sidecar.data_dir

    @property
    def descs(self):
        """Find descriptions in this collection.

        Returns:
            (XgenDesc list): descriptions
        """
        import xgenm
        _descs = []
        for _desc_s in xgenm.descriptions(str(self)):
            _LOGGER.info(' - DESC S %s', _desc_s)
            _desc = _XgenDesc(_desc_s)
            _descs.append(_desc)
        return _descs

    @property
    def local_data_dir(self):
        """Obtain local data dir.

        This is the localised/versioned data folder that this collection
        should be working from if following the pipeline.

        Returns:
            (Dir): local data folder
        """
        _work = pipe.cur_work()
        return _work.to_dir().to_subdir(f'xgen/{_work.base}/{self}')

    @property
    def proj_dir(self):
        """Obtain current project dir for this collection.

        Returns:
            (Dir): project dir
        """
        return self.sidecar.proj_dir.to_subdir(f'xgen/collections/{self}')

    @property
    def sidecar(self):
        """Obtain sidecar file for this collection.

        Returns:
            (XgenSidecar): sidecar
        """
        _work = pipe.cur_work()
        _tokens = [_work.base]
        if self.namespace:
            _tokens.append(self.namespace)
        _tokens.append(str(self))
        _base = '__'.join(_tokens)
        _side = _work.to_file(f'{_base}.xgen', class_=_XgenSidecar)
        if not _side.exists():
            return None
        return _side

    def is_localised(self):
        """Test whether this collection has been localised/versioned.

        Returns:
            (bool): whether localised
        """
        _LOGGER.debug('IS LOCALISED %s', self)
        _LOGGER.debug(' - CUR DIR %s', self.data_dir)
        _LOGGER.debug(' - REQ DIR %s', self.local_data_dir)
        return self.data_dir == self.local_data_dir

    def read_shds(self):
        """Read shaders attached to this collection.

        Returns:
            (dict): desc / shading group data
        """
        _LOGGER.info(' - READ SHDS')
        _shds = {}
        for _desc in self.descs:
            _LOGGER.debug('   - DESC %s %s', _desc, _desc.shp)
            assert _desc.shp
            _sg = single(
                cmds.listConnections(_desc.shp, type='shadingEngine'),
                catch=True)
            _LOGGER.debug('     - SG %s', _sg)
            if _sg:
                _shds[_desc] = _sg
        return _shds


class _XgenDesc(pom.CTransform):
    """Represents an xgen description node."""

    @property
    def col(self):
        """Obtain parent collection for this description.

        Returns:
            (XgenCol): collection
        """
        _col = _XgenCol(self.to_parent())
        assert _col.object_type() == 'xgmPalette'
        return _col

    @property
    def data_dir(self):
        """Obtain data dir for this description.

        Returns:
            (XgenDesc): description
        """
        return self.col.data_dir.to_subdir(str(self))

    @property
    def mesh(self):
        """Obtain mesh for this description.

        Returns:
            (CMesh): mesh
        """
        _LOGGER.debug('READ MESH %s', self)
        _meshes = set()
        for _xsp in self.find_children(type_='xgmSubdPatch', recursive=True):
            _mesh = _xsp.find_connected('mesh')
            _meshes.add(_mesh)
        return single(_meshes)

    @property
    def proj_dir(self):
        """Obtain project dir for this description.

        Returns:
            (Dir): project dir
        """
        return self.col.proj_dir.to_subdir(str(self))


def _mesh_to_xgen_desc(mesh):
    """Find an xgen description from a mesh.

    Args:
        mesh (CMesh): mesh to read

    Returns:
        (XgenDesc): description
    """
    _LOGGER.info('MESH TO XGEN DESC %s', mesh)
    _xsp_shp = single(cmds.listConnections(
        mesh.shp, type='xgmSubdPatch', shapes=True), catch=True)
    _LOGGER.info(' - XSP SHP %s', _xsp_shp)
    if not _xsp_shp:
        return None
    _xsp_tfm = to_parent(_xsp_shp)
    _LOGGER.info(' - XSP TFM %s', _xsp_tfm)
    _desc = _XgenDesc(to_parent(_xsp_tfm))
    # _desc_shp = to_shp(_desc_tfm)
    assert cmds.objectType(_desc.shp) == 'xgmDescription'
    return _desc


def _resolve_proj(path):
    """Resolve an xgen project path.

    ie. replace "${PROJECT}" with the project path.

    Args:
        path (str): tokenised path

    Returns:
        (str): absolute path
    """
    import xgenm
    _token = '${PROJECT}'
    if _token not in path:
        return path
    if not path.startswith(_token):
        raise NotImplementedError(path)
    _rel_path = path[len(_token):]
    _proj = xgenm.getProjectPath().rstrip('/')
    return abs_path(f'{_proj}/{_rel_path}')


def copy_xgen_cols(work, pub, force=False):
    """Copy xgen collections dir to publish.

    Args:
        work (CPWork): source work
        pub (CPOutputFile): target publish
        force (bool): apply sync without confirmation

    Returns:
        (Dir|None): target xgen dir (if any)
    """

    import xgenm

    _LOGGER.info('COPY XGEN COLLECTIONS DIR')

    # Determine src dir
    _proj = Dir(xgenm.getProjectPath())
    _src = _proj.to_subdir('xgen/collections')
    _LOGGER.info(' - SRC %s %s', _src.nice_size(), _src)
    if not _src.exists():
        _LOGGER.info(' - MISSING XGEN SRC %s', _src)
        return None

    # Build output dir
    _trg = pub.to_dir().to_subdir(f'xgen/{work.base}')
    _LOGGER.info(' - TRG %s', _trg)

    if not force:
        qt.ok_cancel('Sync dir?')
    _src.copy_to(_trg, force=force)

    return _trg


def find_xgen_cols():
    """Find xgen collections in the current scene.

    Returns:
        (XgenCol list): collections
    """
    _cols = []
    for _node in pom.find_nodes(type_='xgmPalette'):
        _col = _XgenCol(_node)
        _cols.append(_col)
    return _cols


def localise_xgen_cols(
        edit=False, parent=None, show_previews=False, force=False):
    """Localise xgen collections in the current scene.

    Args:
        edit (bool): edit sidecar files
        parent (QDialog): parent dialog for confirmations
        show_previews (bool): build xgen previews after update
        force (bool): apply update without confirmation
    """
    import xgenm

    _work = pipe.cur_work()
    _xg_proj_path = xgenm.getProjectPath().rstrip('/')
    _LOGGER.info(' - XG PROJ PATH %s', _xg_proj_path)
    _xg_data_root = _work.to_dir().to_subdir(f'xgen/{_work.base}')
    _LOGGER.info(' - XG DATA ROOT %s', _xg_data_root)

    # Find sidecars which needs updating
    _to_update = []
    _size = 0
    for _col in find_xgen_cols():
        _LOGGER.info(' - COL %s', _col)
        _LOGGER.info(' - SIDE %s', _col.sidecar)
        assert not _col.sidecar.ns
        if edit:
            _col.sidecar.edit()
        _cur_dir = _col.sidecar.data_dir
        _LOGGER.info('   - CUR DIR %s', _cur_dir)
        if not _xg_data_root.contains(_cur_dir):
            _LOGGER.info('   - UPDATE REQUIRED')
            _to_update.append(_col.sidecar)
            _size += _cur_dir.size()
        else:
            _LOGGER.info('   - NO UPDATE REQUIRED')

    # Execute update
    if not _to_update:
        _LOGGER.info(' - NOTHING TO UPDATE')
    else:
        if not force:
            qt.ok_cancel(
                f'Apply version and localise {len(_to_update)} '
                f'collection{plural(_to_update)} '
                f'({nice_size(_size)})?\n\n{_xg_data_root}',
                parent=parent)
        _work.save()
        for _side in _to_update:
            _xg_data_path = _xg_data_root.to_subdir(_side.col)
            _side.data_dir.sync_to(_xg_data_path, force=True)
            _side.set_proj_path(_xg_proj_path)
            _side.set_data_path(_xg_data_path, force=True)
        _work.load(force=True)

    if show_previews:
        show_xgen_previews()


def rename_xgen_mesh(
        mesh, new_name, show_previews=False, edit=False, parent=None,
        force=False):
    """Rename an xgen mesh.

    Args:
        mesh (str): mesh to rename
        new_name (str): new name for mesh
        show_previews (bool): build xgen previews after update
        edit (bool): edit sidecar files
        parent (QDialog): parent dialog for confirmations
        force (bool): apply update without confirmation
    """
    import xgenm

    _LOGGER.info('RENAME XGEN MESH %s -> %s', new_name)

    _LOGGER.info(' - MESH %s', mesh)

    # Read attached xgen system
    _desc = _mesh_to_xgen_desc(mesh)
    _LOGGER.info(' - DESC %s', _desc)
    _col = _desc.col
    _side = _desc.col.sidecar
    _new_mesh = new_name
    _new_shp = f'{new_name}Shape'
    _shds = _col.read_shds()
    _LOGGER.info('   - SHDS %s', _shds)

    # Build + update tmp sidecar
    _tmp_side = TMP.to_file(_side.filename)
    xgenm.exportPalette(str(_col), _tmp_side.path)
    _tmp_side = _XgenSidecar(_tmp_side)
    del _side
    _LOGGER.info(' - TMP SIDE %s', _tmp_side)
    _tmp_side.rename_patch(str(mesh), new_name, force=True)
    if edit:
        _tmp_side.edit()

    if not force:
        qt.ok_cancel(
            f'Rename xgen mesh "{mesh}" -> "{new_name}"?', parent=parent)

    # Update ptex
    _LOGGER.info(' - DATA DIR %s', _tmp_side.data_dir)
    _ptxs = _tmp_side.data_dir.find(
        extn='ptx', type_='f', base=str(mesh), class_=True)
    _to_move = []
    for _src_ptx in _ptxs:
        _trg_ptx = _src_ptx.to_file(f'{new_name}.ptx')
        _to_move.append((_src_ptx, _trg_ptx))

    # Move collections
    for _src, _trg in _to_move:
        _src.move_to(_trg)

    # Update scene
    mesh.shp.rename(_new_shp)
    _mesh = mesh.rename(_new_mesh)
    _LOGGER.info(' - UPDATED MESH %s', _mesh)
    xgenm.deletePalette(str(_col))
    xgenm.importPalette(_tmp_side.path, [], '')
    for _desc, _sg in _shds.items():
        cmds.sets(_desc, edit=True, forceElement=_sg)

    if show_previews:
        show_xgen_previews()

    cmds.select(_mesh)


def show_xgen_previews():
    """Build previews on xgen descriptions."""
    import xgenm
    xgenm.ui.createDescriptionEditor(True)
    for _col in find_xgen_cols():
        for _desc in _col.descs:
            cmds.xgmPreview(_desc)


def to_xgen_data_dir():
    """Obtain current xgen data dir for this scene.

    Returns:
        (Dir): data dir
    """
    _data_dirs = set()
    for _col in find_xgen_cols():
        _data_dirs.add(_col.data_dir)
    return single(_data_dirs)


def update_xgen_sidecars(pub, xgen, edit=False, force=False):
    """Update xgen sidecar files to point to publish location.

    Args:
        pub (CPOutputFile): target publish
        xgen (Dir): xgen data dir
        edit (bool): open sidecars in text editor on update (for debugging)
        force (bool): apply updates without confirmation
    """
    _LOGGER.info('UPDATE XGEN SIDECAR FILES')
    _dir = pub.to_dir()
    _xgens = _dir.find(
        depth=1, type_='f', extn='xgen', head=pub.base, class_=True)
    _xg_data = xgen.to_subdir('collection')
    # _proj = abs_path(xgenm.getProjectPath()).rstrip('/')

    for _xgen in _xgens:

        _LOGGER.info(' - XGEN SIDECAR %s', _xgen)
        if edit:
            _xgen.edit()

        _base, _col = _xgen.base.split('__')
        assert _base == pub.base
        _LOGGER.info('   - COL %s', _col)

        _to_replace = set()
        for _line in _xgen.read_lines():
            _tokens = _line.split()
            if len(_tokens) != 2:
                continue
            _key, _val = _tokens
            if _key == 'xgProjectPath':
                _LOGGER.debug('   - LINE        %s', _line)
                _cur_path = _val.rstrip('/')
                _new_path = xgen.path
                if _cur_path == _new_path:
                    continue
                _LOGGER.info('   - CUR PATH %s', _cur_path)
                _LOGGER.info('   - NEW PATH %s', _new_path)
                assert Dir(_new_path).exists()

                _new_line = _line.replace(_cur_path, _new_path)
                _LOGGER.info(' - NEW LINE %s', _new_line)
                _to_replace.add((_line, _new_line))

            elif _key == 'xgDataPath':
                _LOGGER.debug(' - LINE        %s', _line)
                if '${PROJECT}' not in _line:
                    assert Dir(_val).exists()
                    continue
                _cur_path = _val
                _new_path = _xg_data.path
                _new_line = _line.replace(_cur_path, _new_path)
                _to_replace.add((_line, _new_line))

        if _to_replace:
            _body = _xgen.read()
            for _find, _replace in _to_replace:
                _body = _body.replace(_find, _replace)
            _xgen.write(_body, diff=True, wording='Update', force=force)
        else:
            _LOGGER.info(' - NOTHING TO FIX %s', _xgen)


def xgen_cols_are_localised():
    """Check whether xgen collections have been localised in this scene.

    ie. test whether their data dir points to a version folder
    matching this scene.

    Returns:
        (bool): whether xgen collections have been localised
    """
    _work = pipe.cur_work()
    _xg_data_root = _work.to_dir().to_subdir(f'xgen/{_work.base}')
    for _col in find_xgen_cols():
        _LOGGER.info(' - COL %s', _col)
        _LOGGER.info(' - SIDE %s', _col.sidecar)
        assert not _col.sidecar.ns
        _cur_dir = _col.sidecar.data_dir
        _LOGGER.info('   - CUR DIR %s', _cur_dir)
        if not _xg_data_root.contains(_cur_dir):
            _LOGGER.info('   - UPDATE REQUIRED')
            return False
    return True


def xgen_in_use():
    """Test whether xgen is in use in the current scene.

    Returns:
        (bool): whether xgen in use
    """
    if not cmds.pluginInfo('xgenToolkit', query=True, loaded=True):
        return False

    for _type in XGEN_TYPES:
        if cmds.ls(type=_type):
            return True

    return False
