CPrefix: Expanding
CPrefixLocked: Minimum
CPrefixWarning: Minimum
CSequence: Preferred
CSequenceCreate: Minimum
CShotsCreate: Minimum
CShotsText: Expanding
CShotsWarning: Minimum
Job: Preferred
SFps: Minimum
SFpsSave: Minimum
SResSave: Minimum
SResX: Minimum
SResY: Minimum
ShotsTabs: Expanding
ShotsTree: Expanding
label: Preferred
label_2: Preferred
label_3: Preferred
label_4: Preferred
label_5: Preferred
label_6: Preferred
label_7: Preferred
